### ISSUE TITLE
account setting to set default font for codemirror

### ISSUE THREAD

**Issue by bsherin** [bsherin/tactic#1148]
I could have a predetermined list of fonts and let the user pick any one of those, regardless of what is available on their system. Then I would specify fallback fonts that would be used if the font happened to not be there.

``` css
.CodeMirror {
    font-size: 14px;
    font-family: <user default>, Courier, Courier New !important
}
```
